name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/s-nozue/s-nozue.github.io/blob/master/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://github.com/s-nozue/s-nozue.github.io"
demosite = "https://s-nozue-plofile.org"
tags = ["Responsive", "Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "Gurusabarish"
  homepage = "https://twitter.com/nozoc_tohoku"
