name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/s-nozue/s-nozue.github.io/blob/master/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://s-nozue.github.io"
tags = ["Responsive", "Blog", "Portfolio", "Personal"]
min_version = "0.68.0"
publishDir = "docs"

[author]
  name = "S-Nozue"
  homepage = "https://twitter.com/nozoc_tohoku"
